version: "2.4"
services:
  rocketwatch:
    build: rocketwatch
    volumes:
      - ./rocketwatch:/app
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped
