version: "2.4"
services:
  rocketwatch:
    build: rocketwatch
    volumes:
      - ./rocketwatch:/app
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
