version: "2.4"
services:
  rocketwatch:
    build: rocketwatch
    volumes:
      - ./rocketwatch:/app
    restart: unless-stopped
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"